### PR TITLE
Fix header width

### PR DESCRIPTION
**Pull request by lpite**

### CODE REVIEW

**Comment by coderaiser** [comment]
Could you please make screenshot to see what is changed

**Comment by lpite** [comment]
image 
**before**
image
**after**

**Comment by lpite** [comment]
and if wrap text 
image

**Comment by coderaiser** [comment]
What browser do you use?

**Comment by lpite** [comment]
Firefox developer edition,Vivaldi and electron app

**Comment by coderaiser** [comment]
OK and what with default styling is it broken?

**Comment by lpite** [comment]
oh my misstake

**Pull request closed without merging**
